apiVersion: v1
kind: Pod
metadata:
  name: my-webapp
  labels:
    app: my-webapp
spec:
  containers:
  - name: k8s-demo
    image: amitvashist7/mypywebapp:v3
    ports:
    - name: myapp-port
      containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: my-webapp-svc
spec:
  ports:
  - port: 31006
    nodePort: 31006
    targetPort: myapp-port
    protocol: TCP
  selector:
    app: my-webapp
  type: NodePort
